# Generated by Django 2.2.9 on 2020-07-07 13:55

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Serie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criacao', models.DateTimeField(auto_now_add=True)),
                ('modificacao', models.DateTimeField(auto_now=True)),
                ('ano', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(4)])),
                ('turma', models.CharField(choices=[('A', 'Turma A'), ('B', 'Turma B'), ('C', 'Turma C')], max_length=5)),
                ('descricao', models.TextField(blank=True, default='')),
            ],
            options={
                'verbose_name': 'série',
                'verbose_name_plural': 'séries',
                'unique_together': {('ano', 'turma')},
            },
        ),
        migrations.CreateModel(
            name='Disciplinas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criacao', models.DateTimeField(auto_now_add=True)),
                ('modificacao', models.DateTimeField(auto_now=True)),
                ('nome', models.CharField(choices=[('matematica', 'Matemática'), ('portugues', 'Português'), ('historia', 'História'), ('geografia', 'Geografia'), ('ingles', 'Inglês'), ('programacao', 'Programação')], max_length=20)),
                ('descricao', models.TextField(blank=True, default='')),
                ('serie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alunos.Serie')),
            ],
            options={
                'verbose_name': 'disciplina',
                'verbose_name_plural': 'disciplinas',
            },
        ),
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criacao', models.DateTimeField(auto_now_add=True)),
                ('modificacao', models.DateTimeField(auto_now=True)),
                ('nome', models.CharField(max_length=255)),
                ('matricula', models.CharField(max_length=255, unique=True)),
                ('serie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alunos.Serie')),
            ],
            options={
                'verbose_name': 'aluno',
                'verbose_name_plural': 'alunos',
            },
        ),
    ]
